//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using CMS.ContentEngine;
using CMS.Websites;

namespace Generic
{
    /// <summary>
    /// Used only as a "Fake" content type for use with the The IWebPageQueryResultMapper and IContentItemQueryResultMapper to be able to "map" any source that inherits these types and retrieve.
    /// </summary>
    [RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class BaseRedirectForMapping : IWebPageFieldsSource, IBaseRedirect
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Base.Redirect.ForMapping";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


        /// <summary>
        /// PageRedirectionType.
        /// </summary>
        public string PageRedirectionType { get; set; }


        /// <summary>
        /// PageInternalRedirectPage.
        /// </summary>
        public IEnumerable<WebPageRelatedItem> PageInternalRedirectPage { get; set; }


        /// <summary>
        /// PageExternalRedirectURL.
        /// </summary>
        public string PageExternalRedirectURL { get; set; }


        /// <summary>
        /// PageFirstChildClassName.
        /// </summary>
        public string PageFirstChildClassName { get; set; }


        /// <summary>
        /// PageUsePermanentRedirects.
        /// </summary>
        public bool PageUsePermanentRedirects { get; set; }
    }
}