//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Testing
{
	/// <summary>
	/// Represents a content item of type <see cref="WebPageContentItem"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class WebPageContentItem : IContentItemFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Testing.WebPageContentItem";


		/// <summary>
		/// Represents system properties for a content item.
		/// </summary>
		[SystemField]
		public ContentItemFields SystemFields { get; set; }


		/// <summary>
		/// TestName.
		/// </summary>
		public string TestName { get; set; }


		/// <summary>
		/// Question.
		/// </summary>
		public string Question { get; set; }


		/// <summary>
		/// Answer.
		/// </summary>
		public string Answer { get; set; }
	}
}