//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using CMS.ContentEngine;
using CMS.Websites;

namespace Generic
{
    /// <summary>
    /// Used only as a "Fake" content type for use with the The IWebPageQueryResultMapper and IContentItemQueryResultMapper to be able to "map" any source that inherits these types and retrieve.
    /// </summary>
    [RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class BaseMetadataForMapping : IWebPageFieldsSource, IBaseMetadata
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Base.Metadata.ForMapping";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// MetaData_PageName.
		/// </summary>
		public string MetaData_PageName { get; set; }


		/// <summary>
		/// MetaData_Title.
		/// </summary>
		public string MetaData_Title { get; set; }


		/// <summary>
		/// MetaData_Description.
		/// </summary>
		public string MetaData_Description { get; set; }


		/// <summary>
		/// MetaData_Keywords.
		/// </summary>
		public string MetaData_Keywords { get; set; }


		/// <summary>
		/// MetaData_NoIndex.
		/// </summary>
		public bool MetaData_NoIndex { get; set; }


		/// <summary>
		/// MetaData_OGImage.
		/// </summary>
		public IEnumerable<IGenericHasImage> MetaData_OGImage { get; set; }
	}
}