//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;

namespace Testing
{
	/// <summary>
	/// Defines a contract for content types with the <see cref="IXperienceCommunityMemberPermissionConfiguration"/> reusable schema assigned.
	/// </summary>
	public interface IXperienceCommunityMemberPermissionConfiguration
	{
		/// <summary>
		/// Code name of the reusable field schema.
		/// </summary>
		public const string REUSABLE_FIELD_SCHEMA_NAME = "XperienceCommunityMemberPermissionConfiguration";


		/// <summary>
		/// MemberPermissionOverride.
		/// </summary>
		public bool MemberPermissionOverride { get; set; }


		/// <summary>
		/// MemberPermissionIsSecure.
		/// </summary>
		public bool MemberPermissionIsSecure { get; set; }


		/// <summary>
		/// MemberPermissionRoleTags.
		/// </summary>
		public IEnumerable<TagReference> MemberPermissionRoleTags { get; set; }
	}
}