//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace Generic
{
	/// <summary>
	/// Represents a page of type <see cref="Navigation"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Navigation : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "Generic.Navigation";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// NavigationName.
		/// </summary>
		public string NavigationName { get; set; }


		/// <summary>
		/// NavigationType.
		/// </summary>
		public string NavigationType { get; set; }


		/// <summary>
		/// NavigationWebPageItemGuid.
		/// </summary>
		public IEnumerable<WebPageRelatedItem> NavigationWebPageItemGuid { get; set; }


		/// <summary>
		/// NavigationLinkText.
		/// </summary>
		public string NavigationLinkText { get; set; }


		/// <summary>
		/// NavigationLinkUrl.
		/// </summary>
		public string NavigationLinkUrl { get; set; }


		/// <summary>
		/// NavigationLinkTarget.
		/// </summary>
		public string NavigationLinkTarget { get; set; }


		/// <summary>
		/// NavigationIsMegaMenu.
		/// </summary>
		public bool NavigationIsMegaMenu { get; set; }


		/// <summary>
		/// NavigationLinkAlt.
		/// </summary>
		public string NavigationLinkAlt { get; set; }


		/// <summary>
		/// NavigationLinkOnClick.
		/// </summary>
		public string NavigationLinkOnClick { get; set; }


		/// <summary>
		/// NavigationLinkCSS.
		/// </summary>
		public string NavigationLinkCSS { get; set; }


		/// <summary>
		/// IsDynamic.
		/// </summary>
		public bool IsDynamic { get; set; }


		/// <summary>
		/// DynamicCodeName.
		/// </summary>
		public string DynamicCodeName { get; set; }
	}
}