# https://www.youtube.com/watch?v=cUrrdAVmo4I
# to deploy on a version, do git tag v1.0.3-alpha (or anything with v______)
# then this will trigger on it and use the batilla7's action to set version

name: "Deploy to Nuget.org"

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_PATH: './src/XperienceCommunity.Baseline.sln'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build packages'
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore

    - name: version-from-tag-action
      id: version
      uses: Im-Fran/version-from-tag-action@v1.0.3
      with:
        remove-first-character: 'v'
        version-variable-name: 'VERSION'

    - name: 'Pack Project'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ env.VERSION }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: 'Push Package'
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -s ${{ env.NUGET_SOURCE_URL}} -k ${{ secrets.XPERIENCECOMMUNITYBASELINENUGETKEY }}